### PR TITLE
Some compilation fixes

### PR DESCRIPTION
**Pull request by gladk**

### CODE REVIEW

**Comment by eudoxos** [comment]
Hi Anton, thanks. Ack for the first one. For the other one, is `boost::make_shared` qualification necessary? I never use `using namespace std`, and lib/base/Types.hpp says `using boost::make_shared` (so that the code does not have to care which `shared_ptr` is used), there should be no ambiguity. Does the compiler warn? make_shared is used like that in dozens other places as well.

**Comment by gladk** [comment]
Hi Vaclav,

there was an error, using gcc-5.1 with enabled C++11, so I needed to do it
to prepare the package.

**Comment by eudoxos** [comment]
Alright, go ahead. If other make_shared cause troubles (there is about 200 of those, just counted), I will install experimental in a VM a fix it with gcc 5.1 properly. Sounds ok?

**Comment by gladk** [comment]
The only this line caused an error, only in this scope.

**Comment by gladk** [comment]
There are also a lot of warnings about auto_ptr, because it is deprecated already. But they are only warnings at the moment.

**Comment by eudoxos** [comment]
I don't use `auto_ptr` in code, so it must be their headers. I will check what's going on with that make_shared. Thx.

**Comment by gladk** [comment]
Yes, it is in loki:

https://github.com/eudoxos/woodem/blob/master/lib/multimethods/loki/Singleton.h#L158

**Comment by eudoxos** [comment]
Ah, I grepped only **/*.?pp. Will see how to remove it at some point.

**Comment by eudoxos** [comment]
I removed auto_ptr completely in 32ddf8c4ff (replaced by std::unique_ptr).

**Comment by eudoxos** [comment]
This is only loosely related (but I don't want to bother you with PM), but could you please pull https://github.com/eudoxos/minieigen-debian/commit/27a165a17419402ca07ae7584a7a61fa6f82d4ac to git://anonscm.debian.org/cgit/debian-science/minieigen.git ? That unbreaks python3-minieigen which is ATM broken in Debian (the py3k .so it is linked to python2's boost_python, and fails at import-time).

**Pull request merged**
